name: geo-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  # Core scientific python
  - numpy
  - h5py
  - pandas
  - geopandas
  - matplotlib
  - gdal
  - rasterio
  - rasterstats